apiVersion: apps/v1
kind: Deployment
metadata:
  name: humidity-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humidity-service
  template:
    metadata:
      labels:
        app: humidity-service
    spec:
      containers:
      - name: humidity-service
        image: localhost:5000/humidity-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: readings-volume
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: humidity-config
      - name: readings-volume
        configMap:
          name: humidity-readings-config  
