apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-service
  template:
    metadata:
      labels:
        app: temperature-service
    spec:
      containers:
      - name: temperature-service
        image: localhost:5000/temperature-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts: 
        - name: config-volume
          mountPath: /config  
      volumes:  
      - name: config-volume
        configMap:
          name: temperature-config  
